### ISSUE TITLE
Padding is invalid and cannot be removed.

### ISSUE THREAD

**Issue by saineshwar** [VahidN/DNTCaptcha.Core#112]
# I have deployed an application on Azure  wherein log I am getting an error, "**Padding is invalid and cannot be removed**." Call site:- DNTCaptcha.Core.CaptchaCryptoProvider.Decrypt

## Environment

```
DNTCaptcha.Core version: 3.5.0
.NET Core SDK version: 5.0
IDE: VS2019
```

## Example code/Steps to reproduce:

```
 //  AddDNTCaptcha
 services.AddDNTCaptcha(options =>
     // options.UseSessionStorageProvider() // -> It doesn't rely on the server or client's times. Also it's the safest one.
     // options.UseMemoryCacheStorageProvider() // -> It relies on the server's times. It's safer than the CookieStorageProvider.
     options.UseCookieStorageProvider() // -> It relies on the server and client's times. It's ideal for scalability, because it doesn't save anything in the server's memory.
                                        // options.UseDistributedCacheStorageProvider() // --> It's ideal for scalability using `services.AddStackExchangeRedisCache()` for instance.

         // Don't set this line (remove it) to use the installed system's fonts (FontName = "Tahoma").
         // Or if you want to use a custom font, make sure that font is present in the wwwroot/fonts folder and also use a good and complete font!
         // .UseCustomFont(Path.Combine(_env.WebRootPath, "fonts", "name.ttf")) 
         // .AbsoluteExpiration(minutes: 7)
         .ShowThousandsSeparators(false)

 );

```

```
paste your core code
```

## Output:

```
Exception message: Padding is invalid and cannot be removed.
Full Stack trace:

![image](https://user-images.githubusercontent.com/8281689/125033561-1454d500-e0ad-11eb-8988-02fc1f455906.png)

```

**Comment by VahidN** [comment]
[Setting WithEncryptionKey](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Startup.cs#L63) is not optional.

**Comment by saineshwar** [comment]
> [Setting WithEncryptionKey](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Startup.cs#L63) is not optional.

Sir What will be its Size 32 or 64 Length or Some Hash

**Comment by VahidN** [comment]
It doesn't matter here. Because the provided key will hashed with  SHA256 algo and then its first 24 bytes will be used.

**Comment by saineshwar** [comment]
> It doesn't matter here. Because the provided key will hashed with SHA256 algo and then its first 24 bytes will be used.

**Still Same Issue, I have updated settings and provided WithEncryptionKey** 

` services.AddDNTCaptcha(options =>
                options.UseSessionStorageProvider()
                    .ShowThousandsSeparators(false)
                    .WithEncryptionKey("9F3baE2KFTM7m0C^tt%^Ag")
            );` 

![image](https://user-images.githubusercontent.com/8281689/125051583-b6ca8380-e0c0-11eb-8fd9-b1d18f8af781.png)
![image](https://user-images.githubusercontent.com/8281689/125051617-c0ec8200-e0c0-11eb-86b0-afd8a861db6a.png)
![image](https://user-images.githubusercontent.com/8281689/125051657-cba71700-e0c0-11eb-8eb6-feb2be61b769.png)

**Comment by VahidN** [comment]
This error means the library can't decrypt the provided entry, because:
- The entry is provided by some automated bots (that's why you are using a captcha)
- You environment is distributed and you are using a `Session` or `Memory` storage providers to store some temporary values and these values will not be distributed at all. By default, ASP.NET's session is maintained in the RAM of the running web server. However, Windows Azure is a stateless platform, web role instances have no local storage; at any time the web role instance could be moved to a different server in the data center. When the web role instance is moved, the session state is lost. To have a perceived sense of state with a stateless protocol on a stateless web server, you need permanent server side storage that persists even if the web role instance is moved. In this case you should `UseDistributedCacheStorageProvider` or at first try `UseCookieStorageProvider` .

**Comment by saineshwar** [comment]
> This error means the library can't decrypt the provided entry, because:
> 
> * The entry is provided by some automated bots (that's why you are using a captcha)
> * You environment is distributed and you are using a `Session` or `Memory` storage providers to store some temporary values and these values will not be distributed at all. By default, ASP.NET's session is maintained in the RAM of the running web server. However, Windows Azure is a stateless platform, web role instances have no local storage; at any time the web role instance could be moved to a different server in the data center. When the web role instance is moved, the session state is lost. To have a perceived sense of state with a stateless protocol on a stateless web server, you need permanent server side storage that persists even if the web role instance is moved. In this case you should `UseDistributedCacheStorageProvider` or at first try `UseCookieStorageProvider` .

Sir, First I have Tried using **CookieStorageProvider** then tried **SessionStorageProvider**. now after your reply, I have again changed settings and deployed them on prod still find the same results.

Site Link where captcha is used :- [https://onefitnessvue.azurewebsites.net/](https://onefitnessvue.azurewebsites.net/ )

`  services.AddDNTCaptcha(options =>
                options.UseCookieStorageProvider()
                    .ShowThousandsSeparators(false)
                    .WithEncryptionKey("9F3baE2KFTM7m0C^tt%^Ag")
`

**Comment by VahidN** [comment]
- It's working on your site. if I enter a correct captcha value, it says the user name or password is invalid and if I enter a wrong captcha number it says the entered security number is invalid. It doesn't say the user name or password is invalid.
- If you want `SameSiteMode.None` you should set it as the first parameter of `UseCookieStorageProvider`. If you are using CORS here, you should set  [withCredentials: true](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestApiApp/wwwroot/index.html#L136)

**Comment by saineshwar** [comment]
> * It's working on your site. if I enter a correct captcha value, it says the user name or password is invalid and if I enter a wrong captcha number it says the entered security number is invalid. It doesn't say the user name or password is invalid.
> * If you want `SameSiteMode.None` you should set it as the first parameter of `UseCookieStorageProvider`. If you are using CORS here, you should set  [withCredentials: true](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestApiApp/wwwroot/index.html#L136)

Sir, there is some issue with decryption. It working properly but still, it keeps logging this error. I am using Nlog. 

```
public class Program
    {
        public static void Main(string[] args)
        {
            var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
            try
            {
                CreateHostBuilder(args).Build().Run();
            }
            catch (Exception exception)
            {
                logger.Error(exception, "Stopped program because of exception");
                throw;
            }
            finally
            {
                // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
                NLog.LogManager.Shutdown();
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                }).ConfigureLogging(logging =>
                {
                    
                    logging.ClearProviders();
                    logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Error);
                })
                .UseNLog();  // NLog: Setup NLog for Dependency injection
    }
```

**Comment by GhalamborM** [comment]
captcha.core: v4.1
services.AddDNTCaptcha(op=> op.WithEncryptionKey("testKey"));


Error log:
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.GetPaddingLength(ReadOnlySpan`1 block)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(Boolean useAsync, CancellationToken cancellationToken)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.BinaryWriter.Dispose(Boolean disposing)
   at System.IO.BinaryWriter.Dispose()
   at DNTCaptcha.Core.CaptchaCryptoProvider.decrypt(Byte[] data) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\CaptchaCryptoProvider.cs:line 130
   at DNTCaptcha.Core.CaptchaCryptoProvider.Decrypt(String inputText) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\CaptchaCryptoProvider.cs:line 54
   at DNTCaptcha.Core.DNTCaptchaImageController.Show(String data) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\DNTCaptchaImageController.cs:line 165

**Comment by VahidN** [comment]
You can receive malformed data from the bots. It doesn't matter.

**Comment by johnstaveley** [comment]
I tried using cookieprovider and encryption key but still got the error "Padding is invalid and cannot be removed." What is the resolution for this issue?
