### ISSUE TITLE
Returning Stack Trace

### ISSUE THREAD

**Issue by masoud86** [VahidN/DNTCaptcha.Core#121]
Dear VahidN,
I'm using your extension and it works like a charm. There is only a security concern which reported to me as a security vulnerability.
The issue is:
By request a fake token to _Show_ method we can see the stack trace exception.
For example: By requesting below url,
https://localhost/DNTCaptchaImage/Show?data=Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3NoYWRvdw==
we get
```
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.GetPaddingLength(ReadOnlySpan`1 block)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(Boolean useAsync, CancellationToken cancellationToken)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.BinaryWriter.Dispose(Boolean disposing)
   at System.IO.BinaryWriter.Dispose()
   at DNTCaptcha.Core.CaptchaCryptoProvider.decrypt(Byte[] data) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\CaptchaCryptoProvider.cs:line 130
   at DNTCaptcha.Core.CaptchaCryptoProvider.Decrypt(String inputText) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\CaptchaCryptoProvider.cs:line 54
   at DNTCaptcha.Core.DNTCaptchaImageController.Show(String data) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\DNTCaptchaImageController.cs:line 165
```
By checking your repository, I found that, there is a `try catch` causes that this response. So, I can't handle the exception by myself because there is no exception due to try catch mechanism.

```
public IActionResult Show(string data)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(data))
                {
                    return BadRequest("The data is null or empty.");
                }

                var decryptedModel = _captchaProtectionProvider.Decrypt(data);
                if (decryptedModel == null)
                {
                    return BadRequest("Couldn't decrypt the data.");
                }

                var model = _serializationProvider.Deserialize<CaptchaImageParams>(decryptedModel);
                if (model == null)
                {
                    return BadRequest("Couldn't deserialize the model.");
                }

                var decryptedText = _captchaProtectionProvider.Decrypt(model.Text);
                if (decryptedText == null)
                {
                    return BadRequest("Couldn't decrypt the text.");
                }

                var image = _captchaImageProvider.DrawCaptcha(decryptedText, model.ForeColor, model.BackColor, model.FontSize, model.FontName);
                return new FileContentResult(image, "image/png");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to show the captcha image.");
                return BadRequest(ex.ToString());
            }
        }
```
As a suggestion, please don't return `ex.ToString()` in your response (or send it only in debug mode) to avoid this vulnerability.
Thanks in advane.

```
DNTCaptcha.Core version: 4.1.1
.NET Core SDK version: .Net 5
```

**Comment by VahidN** [comment]
I'm not going to change anything. What vulnerability?! The attacker wants to do what with it?! Seriously!
I did it intentionally to show the actual error message to a lot of developers who didn't know why it didn't work for them.
