### ISSUE TITLE
Captcha not work on windows based docker nano Server

### ISSUE THREAD

**Issue by AlirezaSalimi1** [VahidN/DNTCaptcha.Core#14]
I`m using DNTCaptcha 1.4.2 and ASP Core 1.1 when i deploy the project on window server which is using docker nano server i face with this exception and captcha image was not showing in project:

System.TypeInitializationException: The type initializer for 'System.Drawing.KnownColors' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus': The specified module could not be found. (Exception from HRESULT: 0x8007007E)at System.Drawing.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input,GdiplusStartupOutput& output)at System.Drawing.GDIPlus..cctor()
   --- End of inner exception stack trace ---
  at System.Drawing.GDIPlus.RunningOnWindows() at System.Drawing.KnownColors..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.KnownColors.FindColorMatch(Color c)
   at System.Drawing.ColorConverter.StaticConvertFromString(ITypeDescriptorContext context, String s, CultureInfo culture)at System.Drawing.ColorConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)at System.Drawing.ColorTranslator.FromHtml(String htmlColor)
at DNTCaptcha.Core.Providers.CaptchaImageProvider.DrawCaptcha(String message, String foreColor, String backColor, Single fontSize, String fontName)
   at DNTCaptcha.Core.DNTCaptchaImageController.Show(String text, String rndDate, String foreColor,String backColor, Single fontSize, String fontName)
crit: DNTCaptcha.Core.DNTCaptchaImageController[1001]
DrawCaptcha error.

**Comment by VahidN** [comment]
This package is out of my control. follow its issues here
https://github.com/CoreCompat/CoreCompat/issues/3
