### ISSUE TITLE
Failed to show the captcha image.

### ISSUE THREAD

**Issue by GhalamborM** [VahidN/DNTCaptcha.Core#144]
# Summary of the issue
با سلام
جز خطاهای لاگ شده توسط لاگر هستش
```
اطلاعات درخواست:

<properties>
  <property key="SourceContext">DNTCaptcha.Core.DNTCaptchaImageController</property>
  <property key="ActionName">DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core)</property>
  <property key="RequestPath">/dntcaptchaimage/show/</property>
</properties>
```
## Environment

```
DNTCaptcha.Core version:  4.2.0
.NET Core SDK version:  7.0
IDE:  VS 17.4
```

## Example code/Steps to reproduce:

```


   <dnt-captcha asp-captcha-generator-max="9000"
                             asp-captcha-generator-min="1"
                             asp-captcha-generator-language="Persian"
                             asp-placeholder="کد امنیتی به رقم (مانند: 1388)"
                             asp-validation-error-message="لطفا کد امنیتی را به رقم وارد نمائید"
                             asp-font-name="Tahoma"
                             asp-font-size="18"
                             asp-fore-color="#333333"
                             asp-back-color="#ccc"
                             asp-text-box-class="form-control mw-260"
                             asp-text-box-template="<div class='input-group'><span class='input-group-text'><i class='bi bi-unlock'></i></span>{0}</div>"
                             asp-validation-message-class="text-danger"
                             asp-refresh-button-class="bi bi-arrow-repeat text-primary" />
```
## Output:

```
Exception message:
Failed to show the captcha image.

Full Stack trace:
System.Security.Cryptography.CryptographicException: The input data is not a complete block.
   at System.Security.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at System.Security.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(Boolean useAsync, CancellationToken cancellationToken)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at DNTCaptcha.Core.CaptchaCryptoProvider.decrypt(Byte[] data) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\CaptchaCryptoProvider.cs:line 130
   at DNTCaptcha.Core.CaptchaCryptoProvider.Decrypt(String inputText) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\CaptchaCryptoProvider.cs:line 54
   at DNTCaptcha.Core.DNTCaptchaImageController.Show(String data) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\DNTCaptchaImageController.cs:line 165

**Comment by VahidN** [comment]
سلام؛ مهم نيست. يعني باتي رباتي چيزي سعي كرده اطلاعات بي‌ربط ارسال كنه.
