### ISSUE TITLE
Conflict with Swagger

### ISSUE THREAD

**Issue by HesamKashefi** [VahidN/DNTCaptcha.Core#181]
# Summary of the issue
Controller Actions currently don't have HttpMethod attribute which causes Swagger to throw error
```
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Ambiguous HTTP method for action - DNTCaptcha.Core.DNTCaptchaImageController.Refresh (DNTCaptcha.Core). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0

```

## Environment

```
DNTCaptcha.Core version: 5.2.4
.NET Core SDK version: 8.0
IDE: Visual Studio 2022 Version 17.8.6
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message: 
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Ambiguous HTTP method for action - DNTCaptcha.Core.DNTCaptchaImageController.Refresh (DNTCaptcha.Core). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0

Full Stack trace:
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.PrepareGenerateOperation(IGrouping`2 group)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePathsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository, Func`3 operationsGenerator)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePathsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 124
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by HesamKashefi** [comment]
Workaround:
https://stackoverflow.com/a/57454392/5642273
