### ISSUE TITLE
5.2.10 does not run in Debian 10 (buster)

### ISSUE THREAD

**Issue by kobruleht** [VahidN/DNTCaptcha.Core#200]
# Summary of the issue

5.2.10 requires  Skiasharp v 3.116.1  which thorows System.TypeInitializationException in Debian 10 (buster)

## Environment
Debian GNU/Linux 10 (buster)

DNTCaptcha.Core version: 
5.2.10

.NET Core SDK version: 
.NET 9

IDE: 
Visual Studio

## Example code/Steps to reproduce:

```C#
public static class Thumbnail
{
public static byte[] MakeMeAGoodThumbnail(byte[] source, int imageHeight, int imageWidth)
{
// https://stackoverflow.com/questions/73860277/what-is-the-decent-approach-to-resizing-images-in-asp-net-core
SKBitmap image = SKBitmap.Decode(source);
var ratioX = (double)imageWidth / image.Width;
var ratioY = (double)imageHeight / image.Height;
var ratio = Math.Min(ratioX, ratioY);
var newWidth = (int)(image.Width * ratio);
var newHeight = (int)(image.Height * ratio);
var info = new SKImageInfo(newWidth, newHeight);
image = image.Resize(info, SKFilterQuality.High);
using var ms = new MemoryStream();
image.Encode(ms, SKEncodedImageFormat.Png, 100);
return ms.ToArray();
}
}
```

## Output:
```
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKData' threw an exception.
---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /var/www/myapp/libSkiaSharp.so)
libSkiaSharp.so: cannot open shared object file: No such file or directory
/var/www/myapp/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/var/www/myapp/libSkiaSharp: cannot open shared object file: No such file or directory
/var/www/myapp/liblibSkiaSharp: cannot open shared object file: No such file or directory

  at SkiaSharp.SkiaApi.sk_data_new_empty()
  at SkiaSharp.SkiaApi.sk_data_new_empty()  at SkiaSharp.SKData..cctor()
  --- End of inner exception stack trace ---
  at SkiaSharp.SKData.Create(IntPtr address, Int32 length)
  at SkiaSharp.SKBitmap.Decode(ReadOnlySpan`1 buffer)
  at SkiaSharp.SKBitmap.Decode(Byte[] buffer)
....

**Comment by VahidN** [comment]
It seems it has a dependency on a library version ("GLIBC_2.29") that is not available on your system. Check your system's glibc version: Open a terminal and run `strings /lib/x86_64-linux-gnu/libm.so.6 | grep GLIBC` to see the installed glibc version.
If the version is lower than 2.29, you need to upgrade your `glibc`.
+
Have you modified your .csproj to copy [these .so files](https://github.com/VahidN/DNTCaptcha.Core?tab=readme-ov-file#linux-and-containers-support)?
